theme: jekyll-theme-time-machine

plugins:
 - jekyll-sitemap

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<!--   created with free sitemap generation system www.sitemapxml.jp   -->
<url>
<loc>https://sironekosama.github.io/</loc>
<priority>1.0</priority>
<lastmod>2022-04-27T13:53:21+09:00</lastmod>
</url>
<url>
<loc>https://sironekosama.github.io/betuneko.html</loc>
<priority>0.8</priority>
<lastmod>2022-04-27T13:53:21+09:00</lastmod>
</url>
</urlset>
